#!/usr/bin/env bash
# Generates the Plasma splash screen QML for a look-and-feel package.
#
#   gen-splash.sh <package-dir> [--light]
#
# This is the splash Plasma shows AFTER login while the session starts — not the
# Plymouth boot splash, which is a separate thing built by boot/gen-plymouth.sh.
# Neither NeonGrid package shipped one, and nothing set [ksplashrc]KSplash Theme,
# so login fell through to Breeze's black-and-blue Plasma splash.
#
# Self-contained on purpose: no images/ directory, everything is drawn in QML
# from the palette, so the light variant is the same file with different
# numbers rather than a second set of assets to keep in sync.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/../palette.sh"

PKG="${1:?usage: gen-splash.sh <package-dir> [--light]}"
[ "${2:-}" = "--light" ] && neongrid_light

OUT="$PKG/contents/splash"
mkdir -p "$OUT"

# Orbitron is unreadable at UI sizes and is banned everywhere else in this repo,
# but a splash wordmark is exactly the heading case it exists for.
cat > "$OUT/Splash.qml" <<EOF
// Generated by kde/gen-splash.sh from palette.sh — do not edit by hand.
import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root
    color: "#$BG"

    // Plasma drives this: 2 is "start showing", 5 is "session is up".
    property int stage

    onStageChanged: {
        if (stage == 2) {
            introAnimation.running = true;
        } else if (stage == 5) {
            introAnimation.target = content;
            introAnimation.from = 1;
            introAnimation.to = 0;
            introAnimation.running = true;
        }
    }

    // Perspective grid, echoing the wallpaper. Drawn rather than shipped as an
    // image so it scales to any resolution and follows the palette.
    Item {
        anchors.fill: parent
        opacity: 0.18
        clip: true

        Repeater {
            model: 14
            Rectangle {
                color: "#$GREEN"
                height: 1
                width: parent.width
                y: parent.height * 0.55 + Math.pow(index / 14, 2.2) * parent.height * 0.5
            }
        }
        Repeater {
            model: 25
            Rectangle {
                color: "#$GREEN"
                width: 1
                height: parent.height * 0.45
                y: parent.height * 0.55
                x: parent.width / 2 + (index - 12) * parent.width * 0.11
                transform: Rotation {
                    origin.x: 0
                    origin.y: 0
                    angle: (index - 12) * 2.2
                }
            }
        }
    }

    Item {
        id: content
        anchors.fill: parent
        opacity: 0

        Column {
            anchors.centerIn: parent
            spacing: Kirigami.Units.gridUnit

            Text {
                anchors.horizontalCenter: parent.horizontalCenter
                text: "NEONGRID"
                color: "#$GREEN_HERO"
                font.family: "Orbitron"
                font.pointSize: Kirigami.Units.gridUnit * 2
                font.weight: Font.Bold
                font.letterSpacing: Kirigami.Units.gridUnit * 0.6
                textFormat: Text.PlainText
                Accessible.name: text
                Accessible.role: Accessible.StaticText
            }

            // Indeterminate progress: a neon sweep, not a spinner.
            Rectangle {
                anchors.horizontalCenter: parent.horizontalCenter
                width: Kirigami.Units.gridUnit * 18
                height: 2
                color: "#$SURFACE_HI"
                radius: 1
                clip: true

                Rectangle {
                    id: sweep
                    width: parent.width * 0.35
                    height: parent.height
                    radius: 1
                    color: "#$GREEN_HERO"

                    XAnimator on x {
                        from: -sweep.width
                        to: sweep.parent.width
                        duration: 1400
                        loops: Animation.Infinite
                        // Respect "animations off" the way Breeze's splash does.
                        running: Kirigami.Units.longDuration > 1
                    }
                }
            }
        }

        Text {
            anchors {
                bottom: parent.bottom
                right: parent.right
                margins: Kirigami.Units.gridUnit * 1.5
            }
            text: "// C A C H Y O S   ·   P L A S M A"
            color: "#$FG_DIM"
            font.family: "Rajdhani"
            font.pointSize: Kirigami.Units.gridUnit * 0.7
            textFormat: Text.PlainText
            Accessible.name: text
            Accessible.role: Accessible.StaticText
        }
    }

    OpacityAnimator {
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }
}
EOF

echo "  splash -> $OUT/Splash.qml"
