// Generated by kde/gen-splash.sh from palette.sh — do not edit by hand.
import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root
    color: "#0a0e0f"

    // Plasma drives this: 2 is "start showing", 5 is "session is up".
    property int stage

    onStageChanged: {
        if (stage == 2) {
            introAnimation.running = true;
        } else if (stage == 5) {
            introAnimation.target = content;
            introAnimation.from = 1;
            introAnimation.to = 0;
            introAnimation.running = true;
        }
    }

    // Perspective grid, echoing the wallpaper. Drawn rather than shipped as an
    // image so it scales to any resolution and follows the palette.
    Item {
        anchors.fill: parent
        opacity: 0.18
        clip: true

        Repeater {
            model: 14
            Rectangle {
                color: "#3be05c"
                height: 1
                width: parent.width
                y: parent.height * 0.55 + Math.pow(index / 14, 2.2) * parent.height * 0.5
            }
        }
        Repeater {
            model: 25
            Rectangle {
                color: "#3be05c"
                width: 1
                height: parent.height * 0.45
                y: parent.height * 0.55
                x: parent.width / 2 + (index - 12) * parent.width * 0.11
                transform: Rotation {
                    origin.x: 0
                    origin.y: 0
                    angle: (index - 12) * 2.2
                }
            }
        }
    }

    Item {
        id: content
        anchors.fill: parent
        opacity: 0

        Column {
            anchors.centerIn: parent
            spacing: Kirigami.Units.gridUnit

            Text {
                anchors.horizontalCenter: parent.horizontalCenter
                text: "NEONGRID"
                color: "#39ff14"
                font.family: "Orbitron"
                font.pointSize: Kirigami.Units.gridUnit * 2
                font.weight: Font.Bold
                font.letterSpacing: Kirigami.Units.gridUnit * 0.6
                textFormat: Text.PlainText
                Accessible.name: text
                Accessible.role: Accessible.StaticText
            }

            // Indeterminate progress: a neon sweep, not a spinner.
            Rectangle {
                anchors.horizontalCenter: parent.horizontalCenter
                width: Kirigami.Units.gridUnit * 18
                height: 2
                color: "#1b2427"
                radius: 1
                clip: true

                Rectangle {
                    id: sweep
                    width: parent.width * 0.35
                    height: parent.height
                    radius: 1
                    color: "#39ff14"

                    XAnimator on x {
                        from: -sweep.width
                        to: sweep.parent.width
                        duration: 1400
                        loops: Animation.Infinite
                        // Respect "animations off" the way Breeze's splash does.
                        running: Kirigami.Units.longDuration > 1
                    }
                }
            }
        }

        Text {
            anchors {
                bottom: parent.bottom
                right: parent.right
                margins: Kirigami.Units.gridUnit * 1.5
            }
            text: "// C A C H Y O S   ·   P L A S M A"
            color: "#7d8a86"
            font.family: "Rajdhani"
            font.pointSize: Kirigami.Units.gridUnit * 0.7
            textFormat: Text.PlainText
            Accessible.name: text
            Accessible.role: Accessible.StaticText
        }
    }

    OpacityAnimator {
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }
}
